/* soapClient.cpp
   Generated by gSOAP 2.7.9b from getQuote.h
   Copyright(C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.7.9b 2007-09-11 03:24:40 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_SearchService__Search(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::string query, struct SearchService__Result &result)
{	struct SearchService__Search soap_tmp_SearchService__Search;
	soap->encodingStyle = NULL;
	soap_tmp_SearchService__Search.query = query;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_SearchService__Search(soap, &soap_tmp_SearchService__Search);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_SearchService__Search(soap, &soap_tmp_SearchService__Search, "SearchService:Search", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_SearchService__Search(soap, &soap_tmp_SearchService__Search, "SearchService:Search", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_SearchService__Result(soap, &result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_SearchService__Result(soap, &result, "SearchService:Result", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

/* End of soapClient.cpp */
