#include "head.h"

int main(int argc, char** argv){
	//读入文件
	if(argc!=2){
		cout<<"Command Input Error！";
		return -1;
	}
	char* filename=argv[1];
	ifstream fin(filename);
	if(!fin){
		cout<<"Cannot Open File！";
		return -1;
	}
	node s;//初始状态节点
	string temp;
	int i=0,j=0;
	fin>>temp;
	while(j<3){
		while(i<3){
			s.num[j][i]=atoi(temp.c_str());
			i++;
			fin>>temp;
		}
		j++;
		i=0;
	}
	//开始搜索
	stateCount=0;
	state.push_back(node(s.num[0][0],s.num[0][1],s.num[0][2],s.num[1][0],s.num[1][1]
		,s.num[1][2],s.num[2][0],s.num[2][1],s.num[2][2],0,-1));
	open.push_back(state[0].mark);
	//先判断是否有解
	if(solutionExisted(state[0])==false) {
		cout<<"no solution"<<endl;
		return 0;
	}
	while(open.size()!=0){
		if(is_goal(state[open[0]])==true) {
			printResult(state[open[0]]);
			cout<<endl;
			cout<<"total steps:"<<state[open[0]].g<<endl;
			break;
		}
		int a,b;//寻找空格位置，将空格位置(行，列）保存在a，b中
		for(int i=0;i<3;i++){
			for(int j=0;j<3;j++)
				if(state[open[0]].num[i][j]==0) {a=i;b=j;break;}
		}
		if(a==0&&b==0){//空格在0,0处
			if(should_expand(state[open[0]].num[0][1],state[open[0]].num[0][0],state[open[0]].num[0][2],
				state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
				state[open[0]].num[2][1],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][1],state[open[0]].num[0][0],state[open[0]].num[0][2],
					state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
					state[open[0]].num[2][1],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][1]][state[open[0]].num[0][0]][state[open[0]].num[0][2]]
				[state[open[0]].num[1][0]][state[open[0]].num[1][1]][state[open[0]].num[1][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[2][1]][state[open[0]].num[2][2]]=true;
			}
			if(should_expand(state[open[0]].num[1][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
				state[open[0]].num[0][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
				state[open[0]].num[2][1],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[1][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
					state[open[0]].num[0][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
					state[open[0]].num[2][1],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[1][0]][state[open[0]].num[0][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[0][0]][state[open[0]].num[1][1]][state[open[0]].num[1][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[2][1]][state[open[0]].num[2][2]]=true;
			}
		}
		if(a==0&&b==2){//空格在0,2处
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[0][2],state[open[0]].num[0][1],
				state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
				state[open[0]].num[2][1],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[0][2],state[open[0]].num[0][1],
					state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
					state[open[0]].num[2][1],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[0][2]][state[open[0]].num[0][1]]
				[state[open[0]].num[1][0]][state[open[0]].num[1][1]][state[open[0]].num[1][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[2][1]][state[open[0]].num[2][2]]=true;
			}
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[1][2],
				state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[0][2],state[open[0]].num[2][0],
				state[open[0]].num[2][1],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[1][2],
					state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[0][2],state[open[0]].num[2][0],
					state[open[0]].num[2][1],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[0][1]][state[open[0]].num[1][2]]
				[state[open[0]].num[1][0]][state[open[0]].num[1][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[2][1]][state[open[0]].num[2][2]]=true;
			}
		}
		if(a==2&&b==0){//空格在2,0处
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
				state[open[0]].num[2][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[1][0],
				state[open[0]].num[2][1],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
					state[open[0]].num[2][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[1][0],
					state[open[0]].num[2][1],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[0][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[1][1]][state[open[0]].num[1][2]]
				[state[open[0]].num[1][0]][state[open[0]].num[2][1]][state[open[0]].num[2][2]]=true;
			}
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
				state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][1],
				state[open[0]].num[2][0],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
					state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][1],
					state[open[0]].num[2][0],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[0][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[1][0]][state[open[0]].num[1][1]][state[open[0]].num[1][2]]
				[state[open[0]].num[2][1]][state[open[0]].num[2][0]][state[open[0]].num[2][2]]=true;
			}
		}
		if(a==2&&b==2){//空格在2,2处
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
				state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[2][2],state[open[0]].num[2][0],
				state[open[0]].num[2][1],state[open[0]].num[1][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
					state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[2][2],state[open[0]].num[2][0],
					state[open[0]].num[2][1],state[open[0]].num[1][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[0][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[1][0]][state[open[0]].num[1][1]][state[open[0]].num[2][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[2][1]][state[open[0]].num[1][2]]=true;
			}
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
				state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
				state[open[0]].num[2][2],state[open[0]].num[2][1])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
					state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
					state[open[0]].num[2][2],state[open[0]].num[2][1],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[0][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[1][0]][state[open[0]].num[1][1]][state[open[0]].num[1][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[2][2]][state[open[0]].num[2][1]]=true;
			}
		}
		if(a==0&&b==1){//空格在0,1处
			if(should_expand(state[open[0]].num[0][1],state[open[0]].num[0][0],state[open[0]].num[0][2],
				state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
				state[open[0]].num[2][1],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][1],state[open[0]].num[0][0],state[open[0]].num[0][2],
					state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
					state[open[0]].num[2][1],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][1]][state[open[0]].num[0][0]][state[open[0]].num[0][2]]
				[state[open[0]].num[1][0]][state[open[0]].num[1][1]][state[open[0]].num[1][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[2][1]][state[open[0]].num[2][2]]=true;
			}
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[0][2],state[open[0]].num[0][1],
				state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
				state[open[0]].num[2][1],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[0][2],state[open[0]].num[0][1],
					state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
					state[open[0]].num[2][1],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[0][2]][state[open[0]].num[0][1]]
				[state[open[0]].num[1][0]][state[open[0]].num[1][1]][state[open[0]].num[1][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[2][1]][state[open[0]].num[2][2]]=true;
			}
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[1][1],state[open[0]].num[0][2],
				state[open[0]].num[1][0],state[open[0]].num[0][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
				state[open[0]].num[2][1],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[1][1],state[open[0]].num[0][2],
					state[open[0]].num[1][0],state[open[0]].num[0][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
					state[open[0]].num[2][1],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[1][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[1][0]][state[open[0]].num[0][1]][state[open[0]].num[1][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[2][1]][state[open[0]].num[2][2]]=true;
			}
		}
		if(a==1&&b==0){//空格在1,0处
			if(should_expand(state[open[0]].num[1][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
				state[open[0]].num[0][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
				state[open[0]].num[2][1],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[1][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
					state[open[0]].num[0][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
					state[open[0]].num[2][1],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[1][0]][state[open[0]].num[0][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[0][0]][state[open[0]].num[1][1]][state[open[0]].num[1][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[2][1]][state[open[0]].num[2][2]]=true;
			}
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
				state[open[0]].num[1][1],state[open[0]].num[1][0],state[open[0]].num[1][2],state[open[0]].num[2][0],
				state[open[0]].num[2][1],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
					state[open[0]].num[1][1],state[open[0]].num[1][0],state[open[0]].num[1][2],state[open[0]].num[2][0],
					state[open[0]].num[2][1],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[0][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[1][1]][state[open[0]].num[1][0]][state[open[0]].num[1][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[2][1]][state[open[0]].num[2][2]]=true;
			}
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
				state[open[0]].num[2][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[1][0],
				state[open[0]].num[2][1],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
					state[open[0]].num[2][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[1][0],
					state[open[0]].num[2][1],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[0][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[1][1]][state[open[0]].num[1][2]]
				[state[open[0]].num[1][0]][state[open[0]].num[2][1]][state[open[0]].num[2][2]]=true;
			}
		}
		if(a==1&&b==2){//空格在1,2处
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[1][2],
				state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[0][2],state[open[0]].num[2][0],
				state[open[0]].num[2][1],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[1][2],
					state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[0][2],state[open[0]].num[2][0],
					state[open[0]].num[2][1],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[0][1]][state[open[0]].num[1][2]]
				[state[open[0]].num[1][0]][state[open[0]].num[1][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[2][1]][state[open[0]].num[2][2]]=true;
			}
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
				state[open[0]].num[1][0],state[open[0]].num[1][2],state[open[0]].num[1][1],state[open[0]].num[2][0],
				state[open[0]].num[2][1],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
					state[open[0]].num[1][0],state[open[0]].num[1][2],state[open[0]].num[1][1],state[open[0]].num[2][0],
					state[open[0]].num[2][1],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[0][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[1][0]][state[open[0]].num[1][2]][state[open[0]].num[1][1]]
				[state[open[0]].num[2][0]][state[open[0]].num[2][1]][state[open[0]].num[2][2]]=true;
			}
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
				state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[2][2],state[open[0]].num[2][0],
				state[open[0]].num[2][1],state[open[0]].num[1][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
					state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[2][2],state[open[0]].num[2][0],
					state[open[0]].num[2][1],state[open[0]].num[1][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[0][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[1][0]][state[open[0]].num[1][1]][state[open[0]].num[2][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[2][1]][state[open[0]].num[1][2]]=true;
			}
		}
		if(a==2&&b==1){//空格在2,1处
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
				state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][1],
				state[open[0]].num[2][0],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
					state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][1],
					state[open[0]].num[2][0],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[0][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[1][0]][state[open[0]].num[1][1]][state[open[0]].num[1][2]]
				[state[open[0]].num[2][1]][state[open[0]].num[2][0]][state[open[0]].num[2][2]]=true;
			}
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
				state[open[0]].num[1][0],state[open[0]].num[2][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
				state[open[0]].num[1][1],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
					state[open[0]].num[1][0],state[open[0]].num[2][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
					state[open[0]].num[1][1],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[0][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[1][0]][state[open[0]].num[2][1]][state[open[0]].num[1][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[1][1]][state[open[0]].num[2][2]]=true;
			}
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
				state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
				state[open[0]].num[2][2],state[open[0]].num[2][1])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
					state[open[0]].num[1][0],state[open[0]].num[1][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
					state[open[0]].num[2][2],state[open[0]].num[2][1],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[0][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[1][0]][state[open[0]].num[1][1]][state[open[0]].num[1][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[2][2]][state[open[0]].num[2][1]]=true;
			}
		}
		if(a==1&&b==1){//空格在1,1处
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[1][1],state[open[0]].num[0][2],
				state[open[0]].num[1][0],state[open[0]].num[0][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
				state[open[0]].num[2][1],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[1][1],state[open[0]].num[0][2],
					state[open[0]].num[1][0],state[open[0]].num[0][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
					state[open[0]].num[2][1],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[1][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[1][0]][state[open[0]].num[0][1]][state[open[0]].num[1][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[2][1]][state[open[0]].num[2][2]]=true;
			}
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
				state[open[0]].num[1][1],state[open[0]].num[1][0],state[open[0]].num[1][2],state[open[0]].num[2][0],
				state[open[0]].num[2][1],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
					state[open[0]].num[1][1],state[open[0]].num[1][0],state[open[0]].num[1][2],state[open[0]].num[2][0],
					state[open[0]].num[2][1],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[0][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[1][1]][state[open[0]].num[1][0]][state[open[0]].num[1][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[2][1]][state[open[0]].num[2][2]]=true;
			}
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
				state[open[0]].num[1][0],state[open[0]].num[1][2],state[open[0]].num[1][1],state[open[0]].num[2][0],
				state[open[0]].num[2][1],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
					state[open[0]].num[1][0],state[open[0]].num[1][2],state[open[0]].num[1][1],state[open[0]].num[2][0],
					state[open[0]].num[2][1],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[0][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[1][0]][state[open[0]].num[1][2]][state[open[0]].num[1][1]]
				[state[open[0]].num[2][0]][state[open[0]].num[2][1]][state[open[0]].num[2][2]]=true;
			}
			if(should_expand(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
				state[open[0]].num[1][0],state[open[0]].num[2][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
				state[open[0]].num[1][1],state[open[0]].num[2][2])==true)
			{
				state.push_back(node(state[open[0]].num[0][0],state[open[0]].num[0][1],state[open[0]].num[0][2],
					state[open[0]].num[1][0],state[open[0]].num[2][1],state[open[0]].num[1][2],state[open[0]].num[2][0],
					state[open[0]].num[1][1],state[open[0]].num[2][2],state[open[0]].g+1,state[open[0]].mark));
				open.push_back(state[state.size()-1].mark);
				explorered[state[open[0]].num[0][0]][state[open[0]].num[0][1]][state[open[0]].num[0][2]]
				[state[open[0]].num[1][0]][state[open[0]].num[2][1]][state[open[0]].num[1][2]]
				[state[open[0]].num[2][0]][state[open[0]].num[1][1]][state[open[0]].num[2][2]]=true;
			}
		}
		open.erase(open.begin());
		int n=findOpenMin();//找到open表里f值最小的节点位置
		int temp;//将f值
		temp=open[0];//最小的节点
		open[0]=open[n];//放在open表
		open[n]=temp;//的最前面
	}
	return 0;
}